version: 2.1
orbs:
  docker: circleci/docker@1.7.0
workflows:
  build-push-docker:
    jobs:
      - docker/publish:
          image: leonpatmore/kafka-cli
          tag: $CIRCLE_SHA1,latest
          update-description: true
